### ISSUE TITLE
Please add a license file and rename the repository to match the theme

### ISSUE THREAD

**Issue by unixorn** [xuelingkang/xlk-simple-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Also, please rename the repository to match the included `xuelingkang-simple.zsh-theme` file - `zsh-theme` is a very generic name.

Thanks!

**Comment by xuelingkang** [comment]
Okay, it's done.
